CREATE TABLE Event (
  Id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Rule NVARCHAR(300) NOT NULL,
  Subject NVARCHAR(300),
  DeviceId INTEGER UNSIGNED,
  Device NVARCHAR(300),
  Reading NVARCHAR(300),
  TriggeredDT DATETIME,
  ReadingDT DATETIME,
  OriginalReadingDT DATETIME,
  AcknowledgeUrl NVARCHAR(300),
  MessageNumber INTEGER UNSIGNED,
  ParentAccount NVARCHAR(300),
  NetworkId INTEGER UNSIGNED,
  Network NVARCHAR(300),
  AccountId INTEGER UNSIGNED,
  AccountNumber NVARCHAR(300),
  CompanyName NVARCHAR(300),
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Message (
  Id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  EventId INTEGER UNSIGNED NOT NULL,
  MessageId NCHAR(34),
  Recipient NVARCHAR(30),
  Status NVARCHAR(30),
  SentDT DATETIME,
  DeliveredDT DATETIME,
  ErrorCode INTEGER UNSIGNED,
  ErrorMessage NVARCHAR(300),
  Created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_Message_Event
    FOREIGN KEY (EventId) REFERENCES Event (Id)
    ON DELETE CASCADE
);

CREATE EVENT event_CleanHistory_Event
ON SCHEDULE EVERY 1 MONTH
COMMENT 'Delete records older than 3 years'
DO
  DELETE FROM Event 
  WHERE Created < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 3 YEAR);
